/* CONTRACTORS */
export const GET_CONTRACTORS = "GET_CONTRACTORS"
export const GET_CONTRACTORS_SUCCESS = "GET_CONTRACTORS_SUCCESS"
export const GET_CONTRACTORS_FAIL = "GET_CONTRACTORS_FAIL"

/* PROGRESSES */
export const GET_PROGRESSES = "GET_PROGRESSES"
export const GET_PROGRESSES_SUCCESS = "GET_PROGRESSES_SUCCESS"
export const GET_PROGRESSES_FAIL = "GET_PROGRESSES_FAIL"

/* CONTRACTORS DETAIL*/
export const GET_CONTRACTOR_DETAIL = "GET_CONTRACTOR_DETAIL"
export const GET_CONTRACTOR_DETAIL_SUCCESS = "GET_CONTRACTOR_DETAIL_SUCCESS"
export const GET_CONTRACTOR_DETAIL_FAIL = "GET_CONTRACTOR_DETAIL_FAIL"

/**
 * add user
 */
export const ADD_NEW_CONTRACTOR = "ADD_NEW_CONTRACTOR"
export const ADD_CONTRACTOR_SUCCESS = "ADD_CONTRACTOR_SUCCESS"
export const ADD_CONTRACTOR_FAIL = "ADD_CONTRACTOR_FAIL"

/**
 * Edit user
 */
export const UPDATE_CONTRACTOR = "UPDATE_CONTRACTOR"
export const UPDATE_CONTRACTOR_SUCCESS = "UPDATE_CONTRACTOR_SUCCESS"
export const UPDATE_CONTRACTOR_FAIL = "UPDATE_CONTRACTOR_FAIL"

/**
 * Delete user
 */
export const DELETE_CONTRACTOR = "DELETE_CONTRACTOR"
export const DELETE_CONTRACTOR_SUCCESS = "DELETE_CONTRACTOR_SUCCESS"
export const DELETE_CONTRACTOR_FAIL = "DELETE_CONTRACTOR_FAIL"

export const GET_DOCSLIST = "GET_DOCSLIST"
export const GET_DOCSLIST_SUCCESS = "GET_DOCSLIST_SUCCESS"
export const GET_DOCSLIST_FAIL = "GET_DOCSLIST_FAIL"

export const ASSIGN_USER = "progress/ASSIGN_USER"
export const CHANGE_STATUSES = "progress/CHANGE_STATUSES"

export const SET_MANAGERS = "progress/SET_MANAGERS"
export const SET_ENGAGEMENTS = "progress/SET_ENGAGEMENTS"

export const SETTER = "progress/SETTER"
