export const FETCH_CHATS = "chat/FETCH_CHATS"
export const GET_CHAT_BY_ID = "chat/GET_CHAT_BY_ID"
export const CREATE_CHAT = "chat/CREATE_CHAT"
export const SET_SELECTED_CHAT = "chat/SET_SELECTED_CHAT"
export const SET_CHAT_LIST = "chat/SET_CHAT_LIST"
export const ADD_MEMBER = "chat/ADD_MEMBER"
export const UPDATE_CHAT = "chat/UPDATE_CHAT"
export const UPDATE_CHAT_LAST_MESSAGE = "chat/UPDATE_CHAT_LAST_MESSAGE"
export const ADD_CHAT = "chat/ADD_CHAT"

export const FETCH_MESSAGES_BY_ID = "chat/FETCH_MESSAGES"
export const UPDATE_MESSAGE = "chat/UPDATE_MESSAGE"
export const DELETE_MESSAGE_BY_ID = "chat/DELETE_MESSAGE_BY_ID"
export const CREATE_MESSAGE = "chat/CREATE_MESSAGE"

export const SET_MESSAGES = "chat/SET_MESSAGES"
export const SET_REPLYING_MESSAGE = "chat/SET_REPLYING_MESSAGE"
export const SET_EDITING_MESSAGE = "chat/SET_EDITING_MESSAGE"
export const SET_SELECTED_CHAT_MESSAGES = "chat/SET_SELECTED_CHAT_MESSAGES"
export const ADD_MESSAGE = "chat/ADD_MESSAGE"
export const DELETE_MESSAGE = "chat/DELETE_MESSAGE"
export const EDIT_MESSAGE = "chat/EDIT_MESSAGE"

export const SETTER = "chat/SETTER"
